# Generated by Django 5.1.4 on 2025-01-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_capacity_alter_tour_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter discount percentage (e.g., 10 for 10%)', max_digits=10, null=True),
        ),
    ]
