# Generated by Django 5.1.4 on 2025-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='adults',
        ),
        migrations.AddField(
            model_name='booking',
            name='kids',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
